title: "Young Choi - The Crafted Life"
description: "A journey through research, teaching, and engineering — turning struggles into growth."
url: "https://USERNAME.github.io"
baseurl: "/system_engineer"

remote_theme: "mmistakes/minimal-mistakes@4.24.0"

markdown: kramdown
highlighter: rouge
permalink: /:categories/:title/
timezone: America/Bogota

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji
  - jekyll-include-cache

author:
  name: "Choi Young"
  avatar: /assets/images/avatar-placeholder.png
  bio: "Physicist → applied engineering path. Science, imaging, and life design."
  location: "Santa Marta, Colombia"

nav:
  - title: "Home"
    url: "{{ site.baseurl }}/"
  - title: "Study"
    url: "{{ site.baseurl }}/study/"
    children:
      - title: "Engineering"
        url: "{{ site.baseurl }}/study/engineering/"
  - title: "Research"
    url: "{{ site.baseurl }}/research/"
  - title: "Education"
    url: "{{ site.baseurl }}/education/"
